
POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "ravi123",
    "password": "ravi@456"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "ravi123",
    "password": "ravi@456"
}